# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecf6374254d317e32e416007c352e4d4aac20cff267a2dc858e4fdea7d250efad736ed0e7d487461b283ce5a4dd5a33c6d982e87c720e34a8002a4c9332bde52

test:
  secret_key_base: a7d148f44b4c041b31c81b2dd16eb0033cc0a7249630459947780ee7c95c0ef3a88bbf765663524c8646534cccf59d30d63f0007af9b7e6bbf04a7313a4aad6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
